name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18    
  Lint: 
  
    runs-on: ubuntu-latest

    steps:
       - name: Super-Linter
         uses: github/super-linter@v4.9.4
         env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: nikhilbattula9-patch-1
          GITHUB_TOKEN: ${{ secrets.toksec }} 
          LOG_FILE: super-Linter.log
