name: Lib - Validate Branch Name


on:
  push:
    branches: [ "master" ]
# env:
#   DAY_OF_WEEK: "Always Monday"

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      output3: ${{ steps.job1.outputs.initial }}
    steps:
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step1
      - run:  |  
           echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
           initial=${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
           echo initial
  job3:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
